### ISSUE TITLE
Works 100%

### ISSUE THREAD

**Issue by asfsecure** [inadvertently/Blame#2]
This is the best bot ever!

**Comment by inadvertently** [comment]
Fax

**Comment by jude1337** [comment]
how did u get it working?
when i run 'pip install -r requirements.txt' i just get errors.

**Comment by inadvertently** [comment]
> how did u get it working? when i run 'pip install -r requirements.txt' i just get errors.

Open an issue with some context

**Comment by jude1337** [comment]
have u got discord?
